import sqlite3 [cite: 90]
import json [cite: 91]
from datetime import datetime [cite: 92]

class Sis: [cite: 103]
    def __init__(self): [cite: 94]
        self.db = sqlite3.connect('loja.db') [cite: 95, 97]
        self.c = self.db.cursor() [cite: 96, 98]
        self.c.execute('''CREATE TABLE IF NOT EXISTS ped (
            id INTEGER PRIMARY KEY, cli TEXT, itens TEXT,
            tot REAL, st TEXT, dt TEXT, tp TEXT)''') [cite: 99, 100, 101]
        self.db.commit() [cite: 102]

    def add_ped(self, n, its, t): [cite: 119]
        dt = datetime.now().strftime("%Y-%m-%d %H:%M:%S") [cite: 120]
        tot = 0 [cite: 121]
        for i in its: [cite: 122]
            if i['tipo'] == 'normal': [cite: 123]
                tot += i['p'] * i['q'] [cite: 124]
            elif i['tipo'] == 'desc10': [cite: 125, 130]
                tot += i['p'] * i['q'] * 0.9 [cite: 136]
            elif i['tipo'] == 'desc20': [cite: 132, 137]
                tot += i['p'] * i['q'] * 0.8 [cite: 138]
            elif i['tipo'] == 'frete_gratis': [cite: 140, 144]
                tot += i['p'] * i['q'] [cite: 144]

        if t == 'vip': [cite: 147]
            tot = tot * 0.95 [cite: 151]
        elif t == 'corporativo': [cite: 153, 154]
            tot = tot * 0.90 [cite: 157]

        its_str = json.dumps(its) [cite: 176]
        self.c.execute("INSERT INTO ped (cli, itens, tot, st, dt, tp) VALUES (?, ?, ?, ?, ?, ?)",
                       (n, its_str, tot, 'pendente', dt, t)) [cite: 177, 178]
        self.db.commit() [cite: 177]

        if t == 'normal': [cite: 179]
            print(f"Email enviado para {n}: Pedido recebido!") [cite: 180]
        elif t == 'vip': [cite: 181]
            print(f"Email enviado para {n}: Pedido recebido!") [cite: 181]
            print(f"SMS enviado para {n}: Pedido VIP recebido!") [cite: 181]
        elif t == 'corporativo': [cite: 182]
            print(f"Email enviado para {n}: Pedido recebido!") [cite: 183]
            print(f"Notificacao enviada ao gerente de conta de {n}") [cite: 183]
        return self.c.lastrowid [cite: 184]

    def get_ped(self, id): [cite: 187]
        self.c.execute("SELECT * FROM ped WHERE id=?", (id,)) [cite: 189, 190]
        r = self.c.fetchone() [cite: 193]
        if r: [cite: 194]
            return {'id': r[0], 'cli': r[1], 'itens': json.loads(r[2]),
                    'tot': r[3], 'st': r[4], 'dt': r[5], 'tp': r[6]} [cite: 195, 196, 198, 199, 201]
        return None [cite: 203]

    def upd_st(self, id, s): [cite: 231]
        p = self.get_ped(id) [cite: 232]
        if p: [cite: 233]
            self.c.execute("UPDATE ped SET st=? WHERE id=?", (s, id)) [cite: 234]
            self.db.commit() [cite: 234]
            if s == 'aprovado': [cite: 235]
                print(f"Email enviado para {p['cli']}: Pedido aprovado!") [cite: 236]
                if p['tp'] == 'vip': [cite: 236]
                    print(f"SMS enviado para {p['cli']}: Pedido aprovado!") [cite: 237]
            elif s == 'enviado': [cite: 238]
                print(f"Email enviado para {p['cli']}: Pedido enviado") [cite: 238]
            elif s == 'entregue': [cite: 239]
                print(f"Email enviado para {p['cli']}: Pedido entregue!") [cite: 239]
                if p['tp'] == 'vip': [cite: 239]
                    pts = int(p['tot'] * 2) [cite: 240]
                    print(f"Cliente VIP ganhou {pts} pontos!") [cite: 241]
                elif p['tp'] == 'corporativo': [cite: 242]
                    pts = int(p['tot'] * 1.5) [cite: 243]
                    print(f"Cliente corporativo ganhou {pts} pontos!") [cite: 244]
                else: [cite: 245]
                    pts = int(p['tot']) [cite: 225, 246]
                    print(f"Cliente ganhou {pts} pontos!") [cite: 247]

    def calc_tot_cli(self, n): [cite: 248]
        self.c.execute("SELECT * FROM ped WHERE cli=?", (n,)) [cite: 249]
        rs = self.c.fetchall() [cite: 250]
        t = 0 [cite: 252]
        for r in rs: [cite: 254]
            t += r[3] [cite: 256]
        return t [cite: 258]

    def gerar_rel(self, tipo): [cite: 267]
        if tipo == 'vendas': [cite: 267]
            self.c.execute("SELECT * FROM ped") [cite: 268, 270]
            rs = self.c.fetchall() [cite: 269]
            print("=== RELATORIO DE VENDAS ===") [cite: 271]
            tot_g = 0 [cite: 272]
            for r in rs: [cite: 274]
                print(f"Pedido #{r[0]} Cliente: {r[1]} Total: R${r[3]:.2f} Status: {r[4]}") [cite: 276, 277, 278, 292]
                tot_g += r[3] [cite: 283]
            print(f"Total Geral: R${tot_g:.2f}") [cite: 293]
            with open('rel_vendas.txt', 'w') as f: [cite: 294]
                f.write(f"Total de vendas: {tot_g}") [cite: 295]
        elif tipo == 'clientes': [cite: 296]
            self.c.execute("SELECT DISTINCT cli, tp FROM ped") [cite: 297]
            rs = self.c.fetchall() [cite: 298]
            print("=== RELATORIO DE CLIENTES ===") [cite: 299]
            for r in rs: [cite: 300]
                n = r[0] [cite: 303]
                tp = r[1] [cite: 304]
                tot = self.calc_tot_cli(n) [cite: 307]
                print(f"Cliente: {n} ({tp}) Total gasto: R${tot:.2f}") [cite: 308, 309]
            with open('rel_clientes.txt', 'w') as f: [cite: 310]
                for r in rs: [cite: 311]
                    f.write(f"{r[0]}, {r[1]}\n") [cite: 312]

    def proc_pag(self, id, m, vl): [cite: 313]
        p = self.get_ped(id) [cite: 314]
        if not p: [cite: 328]
            return False [cite: 315]
        if vl < p['tot']: [cite: 331]
            print("Valor insuficiente!") [cite: 316]
            return False [cite: 334]

        if m == 'cartao': [cite: 317]
            print("Processando pagamento com cartao...") [cite: 318]
            print("Cartao validado!") [cite: 319]
            self.upd_st(id, 'aprovado') [cite: 320]
            return True [cite: 368]
        elif m == 'pix': [cite: 369]
            print("Gerando QR Code PIX...") [cite: 370]
            print("PIX recebido!") [cite: 371]
            self.upd_st(id, 'aprovado') [cite: 372]
            return True [cite: 373]
        elif m == 'boleto': [cite: 374]
            print("Gerando boleto...") [cite: 375]
            print("Boleto gerado!") [cite: 376]
            return True [cite: 377]
        else: [cite: 378]
            print("Metodo de pagamento invalido!") [cite: 379]
            return False [cite: 379]

    def validar_estoque(self, its): [cite: 380]
        est = {'produto1': 100, 'produto2': 50, 'produto3': 75} [cite: 382, 383]
        for i in its: [cite: 384]
            if i['nome'] not in est: [cite: 385]
                print(f"Produto {i['nome']} nao encontrado!") [cite: 386]
                return False [cite: 386]
            if est[i['nome']] < i['q']: [cite: 387]
                print(f"Estoque insuficiente para {i['nome']}!") [cite: 388]
                return False [cite: 388]
        return True [cite: 389]

    def cancelar_pedido(self, id): [cite: 390]
        self.c.execute("UPDATE ped SET st=? WHERE id=?", ('cancelado', id)) [cite: 392]
        self.db.commit() [cite: 393]
        print(f"Pedido {id} cancelado") [cite: 394]

    def close(self): [cite: 400]
        self.db.close() [cite: 402]

class PedEspecial(Sis): [cite: 405]
    def add_ped(self, n, its, t): [cite: 413]
        dt = datetime.now().strftime('%Y-%m-%d %H:%M:%S') [cite: 414]
        tot = 0 [cite: 415]
        for i in its: [cite: 410]
            if i['tipo'] == 'normal': [cite: 416]
                tot += i['p'] * i['q'] [cite: 417, 418]
            elif i['tipo'] == 'desc10': [cite: 423, 425]
                tot += i['p'] * i['q'] * 0.9 [cite: 450]
            elif i['tipo'] == 'desc20': [cite: 427, 451]
                tot += i['p'] * i['q'] * 0.8 [cite: 454]
        tot = tot * 1.15 [cite: 449]
        its_str = json.dumps(its) [cite: 452]
        self.c.execute("INSERT INTO ped (cli, itens, tot, st, dt, tp) VALUES (?, ?, ?, ?, ?, ?)",
                       (n, its_str, tot, 'pendente', dt, t)) [cite: 453, 455]
        self.db.commit() [cite: 456]
        print(f"Email especial enviado para {n}: Pedido especial recebido!") [cite: 457]
        return self.c.lastrowid [cite: 457]

    def upd_st(self, id, s): [cite: 458]
        p = self.get_ped(id) [cite: 461]
        if p: [cite: 462]
            self.c.execute("UPDATE ped SET st=? WHERE id=?", (s, id)) [cite: 464]
            self.db.commit() [cite: 464]
            print(f"Pedido especial {id} > {s}") [cite: 465]

def main(): [cite: 463]
    s = Sis() [cite: 467]
    its1 = [{'nome': 'produto1', 'p': 100, 'q': 2, 'tipo': 'normal'},
            {'nome': 'produto2', 'p': 50, 'q': 1, 'tipo': 'desc10'}] [cite: 469, 471, 472, 474, 481]
    if s.validar_estoque(its1): [cite: 478]
        id1 = s.add_ped('Joao Silva', its1, 'normal') [cite: 482]
        print(f"Pedido {id1} criado!") [cite: 483]
        s.proc_pag(id1, 'cartao', 250) [cite: 486]
        s.upd_st(id1, 'enviado') [cite: 487]
        s.upd_st(id1, 'entregue') [cite: 499]

    its2 = [{'nome': 'produto3', 'p': 200, 'q': 1, 'tipo': 'desc20'}] [cite: 500]
    if s.validar_estoque(its2): [cite: 501]
        id2 = s.add_ped('Maria Santos', its2, 'vip') [cite: 502]
        s.proc_pag(id2, 'pix', 160) [cite: 503]

    its3 = [{'nome': 'produto1', 'p': 100, 'q': 5, 'tipo': 'normal'}] [cite: 504]
    if s.validar_estoque(its3): [cite: 505]
        id3 = s.add_ped('Empresa XYZ', its3, 'corporativo') [cite: 506, 508]
        s.proc_pag(id3, 'boleto', 500) [cite: 507]

    s.gerar_rel('vendas') [cite: 511]
    print() [cite: 513]
    s.gerar_rel('clientes') [cite: 515]
    s.close() [cite: 517]

if __name__ == '__main__': [cite: 520]
    main() [cite: 521]